# Generated by Django 3.0.5 on 2020-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200603_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.TextField(max_length=1500),
        ),
    ]
